### ISSUE TITLE
[BUG] Sentry post-round behaviour

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#21]
If the sentry on a losing team is still alive after a round ends, it will not disable and continue shooting.

Honestly i think keeping this in would be funny tho.

**Comment by kingofings** [comment]
I think i already identified what's causing this. The wrangler props has a hook in FindTarget, where the cooldown is always set to false since there is no cooldown when holstering anymore (unless sapped) this is not a bug really it's more of an oversight.

Priority currently low until I'm finished with my break, not gamebreaking.

**Comment by kingofings** [comment]
The bug has been fixed an will be pushed in the next update
